### ISSUE TITLE
executable path

### ISSUE THREAD

**Issue by fdufnews** [lurk101/pshell#11]
in V1.2.9, executable search order is current directory followed by /bin directory

Yes, but it only works if current directory is /
If you are currently in a subdirectory and the program is in /bin you 've got an "unknown command" message
If you are currently in a subdirectory and the program is in this subdirectory you 've got an "unknown command" message
From a subdirectory, it works if the full path is specified ../bin/progname

Probably not really a problem but should be explain at least

**Comment by lurk101** [comment]
Thanks for the report. fixed by commit 39d9cb8.
