### ISSUE TITLE
status seems to return wrong values

### ISSUE THREAD

**Issue by fdufnews** [lurk101/pshell#14]
Here is the content of the file system on my pico and the values returned by status.
The block size is 4096 so 22 blocks should be used if I am not mistaken
```
/: ls /bin

     428 blink
     664 sieve

/: ls /code

     580 blink.c
     364 clocks.c
     128 clrscr.c
     121 crash.c
      68 essai.txt
     387 essaigetchar.c
     976 fade.c
      51 hello.c
    2440 life.c
    5357 lorenz.c
    2104 penta.c
     222 pi.c
     370 pi2.c
     558 sieve.c
     362 sine.c
     673 string.c
     256 tictoc.c
   10188 wumpus.c

/: status

total blocks 448, block size 4096, used 20 (1792K), 4.5% used.

/: 
```
I first thought that /bin was not taken into account but If I compile wumpus.c to /bin/wumpus, new blocks are used
```
/code/: ls /bin

     428 blink
     664 sieve
    8860 wumpus
```
considering the size of wumpus i suppose two new blocks are used. But status returns
```
/code/: status


total blocks 448, block size 4096, used 23 (1792K), 5.1% used.
```
If I delete /bin/wumpus the original status is returned
If I now make a copy of a small file say essai.txt
```
/code/: cp essai.txt essai2.txt

file /code/essai.txt copied to /code/essai2.txt

/code/: ls

     580 blink.c
     364 clocks.c
     128 clrscr.c
     121 crash.c
      68 essai.txt
      68 essai2.txt
     387 essaigetchar.c
     976 fade.c
      51 hello.c
    2440 life.c
    5357 lorenz.c
    2104 penta.c
     222 pi.c
     370 pi2.c
     558 sieve.c
     362 sine.c
     673 string.c
     256 tictoc.c
   10188 wumpus.c

/code/: status

total blocks 448, block size 4096, used 20 (1792K), 4.5% used.
```
So it seems that small files are not taken into account or that they are all stored in one block (??)

**Comment by fdufnews** [comment]
Stupid me .
I have found the answer on the [littlefs github
](https://github.com/littlefs-project/littlefs/blob/40dba4a556e0d81dfbe64301a6aa4e18ceca896c/DESIGN.md#files)
I should have reread the code a little before opening this issue and seen that the block count is given by littlefs library not your code.
So small files, not always consume more blocks as they can share block ressources.

**Comment by lurk101** [comment]
Glad you figured it out.
