### ISSUE TITLE
Program data exceptions data segment

### ISSUE THREAD

**Issue by DazzlingOkami** [lurk101/pshell#19]
Hello:
I use CC to compile this code to prompt "program data exceptions data segment"
```
char tmp[4096];
int main(){
return 0;
}
```
I found that the data side size defined in the code is 16k，but I only used 4k.
`#define DATA_ BYTES (16 * K)       // data segment size`
What is the problem?

**Comment by lurk101** [comment]
fixed with commit 1545ee396b7679cd8665b24064d601d670e6dea9
