### ISSUE TITLE
Fixed serious compound assign bugs

### ISSUE THREAD

**Issue by HPCguy** [lurk101/pshell#22]
Over in HPCguy/Squint, everything in pull request #82 above line 960 and the entirety of the follow-on pull request #83 provides a fix for really bad pointer bugs.  Squint still doesn't have forward declarations, hence the cut and paste sections in pull request #83, that could esily be consolidated in a small function.

**Comment by lurk101** [comment]
Fixed by 3716f27e45e37be9ccdc7a4152c7e129189899c1
