### ISSUE TITLE
SD Card support ?

### ISSUE THREAD

**Issue by CHiPs44** [lurk101/pshell#23]
Hello,

The idea of having the file system on the internal flash is great as it makes the project self-contained, but I use my Pico for other things (essentially VGA stuff with the VGA demo board) and the files get wiped every time.

Does anyone has implemented SD card support, especially with the VGA demo board (which has a special way to hook it up as there aren't much GPIO pins left with RGB555 using 15 pins) ?

It has already been done for the PT52 project, cf. https://gitlab.com/DarkElvenAngel/pt52.

**Comment by lurk101** [comment]
I'd be interested in porting that and I have the VGA demo board. The only problem is that that board leaves no UART pins open and I do all my development with SWD and a UART port.

**Comment by lurk101** [comment]
Oh! I see from the schematic that GPIO 20-21 are available if I don't jumper for 4 bit SD card mode.

**Comment by CHiPs44** [comment]
I don't know if SD is available even in 1bit mode if you use thé uart pins.

**Comment by lurk101** [comment]
Should be available, all required signals are connected.

**Comment by CHiPs44** [comment]
It should work, see page 30 of https://datasheets.raspberrypi.com/rp2040/hardware-design-with-rp2040.pdf

**Comment by CHiPs44** [comment]
(and I think you have to cut out PCB traces to be able to use UART)

**Comment by lurk101** [comment]
The board design implies that a PIO is used instead of the built-in controller for the SPI interface. No need to cut traces.

**Comment by lurk101** [comment]
sd card support for vgaboard implemented with commit aea5d5484f23c5426f1d2a5f2b48dc4601e4d586

**Comment by CHiPs44** [comment]
I'll have a look ASAP!

**Comment by CHiPs44** [comment]
I did a try and my 16 GB SD card doesn't seem to want to be formatted.

The shell does ask me to format it and returns immediately to the prompt without mount it.

I'll try to format it with fuse tools.
