### ISSUE TITLE
testing on pico rp2040

### ISSUE THREAD

**Issue by develone** [lurk101/pshell#30]
These are the changes I made to pshell/cc/cc_extrns.h for the pshell to work when cmake .. -DPICO_BOARD=pico for pico rp2040
-    {"uart_get_dreq_num", 2, uart_defines, uart_get_dreq_num, 0},
+    {"uart_get_dreq_num", 2, uart_defines, uart_get_dreq, 0},
     {"uart_get_hw", 1, uart_defines, uart_get_hw, 0},
     {"uart_get_index", 1, uart_defines, uart_get_index, 0},
     {"uart_get_instance", 1, uart_defines, uart_get_instance, 0},
-    {"uart_get_reset_num", 1, uart_defines, uart_get_reset_num, 0}, 
+    {"uart_get_reset_num", 1, uart_defines, uart_get_instance, 0}, 
     {"uart_getc", 1, uart_defines, uart_getc, 0},
     {"uart_init",  2, uart_defines,uart_init, 0},
     {"uart_is_enabled", 1, uart_defines, uart_is_enabled, 0},
@@ -247,7 +247,7 @@
     {"uart_set_fifo_enabled", 2,  uart_defines, uart_set_fifo_enabled, 0},
     {"uart_set_format", 3, uart_defines, uart_set_format, 0},
     {"uart_set_hw_flow", 3, uart_defines, uart_set_hw_flow, 0},
-    {"uart_set_irqs_enabled", 3, uart_defines, uart_set_irqs_enabled, 0},
+    {"uart_set_irqs_enabled", 3, uart_defines, uart_set_irq_enables, 0},

**Comment by lurk101** [comment]
Thanks. I've made the recommended changes in the dev branch. See commit 098a68c
Can you verify that I got it right? I currently don't have an RP2040 set up for testing.

**Comment by develone** [comment]
Thanks for quick upadate.
tested test-dev built on Raspberry Pi5
commit 5c30b565a5fb598862a6ef3426c7498bb271cbd4 (HEAD -> test-dev, origin/test-dev)
Author: Edward Vidal Jr <develone@sbcglobal.net>
Date:   Fri Nov 1 06:14:21 2024 -0600
rm -rf build
mkdir build
cd build

cmake .. -DPICO_BOARD=pico -DPICO_PLATFORM=rp2040
make
cp pshell.uf2 /media/devel/RPI-RP2/

mount 
hex a64.bin
/: version

Pico Shell , LittleFS v2.9, Vi 0.9.1, SDK v2.0.0
pshell worked okay with minicom /dev/ttyACM0

mkdir build-rp2350
cd build-rp2350
cmake .. -DPICO_BOARD=pico2 -DPICO_PLATFORM=rp2350
make
cp pshell.uf2 /media/devel/RP2350/

mount 
hex a64.bin
/: version                                                                      
                                                                                
Pico Shell , LittleFS v2.9, Vi 0.9.1, SDK v2.0.0
pshell worked okay with minicom /dev/ttyACM0
