### ISSUE TITLE
Halfwords for bytecode?

### ISSUE THREAD

**Issue by HPCguy** [lurk101/pshell#7]
What would be the effect of using halfwords, or even bytes, for the VM IR on the Pico?  I'm not familiar enough with the architecture to know how it would impact performance. One clear benefit is that you could fit larger programs in the tight memory space on the Pico.  Maybe this could be another Makefile configured option?

**Comment by lurk101** [comment]
Yes, that would certainly compact the executable and the thought had
crossed my mind.

- The CM0+ cannot do unaligned accesses, so the 'everything's a 32 bit
word' approach keeps things super simple.
- Not sure if I'll get there but the end goal is native CM0+ Thumb code
generation. Enhancing the VM doesn't move in that direction.

In any case, I've other things to tend to and will reassess later.
