### ISSUE TITLE
Enhance VM for faster execution

### ISSUE THREAD

**Issue by HPCguy** [lurk101/pshell#8]
You might want to create new "Immediate" IR nodes that take an immediate argument. Example:

in run():
case AddIMM: 
   a.i += *pc++;

in gen():
   int *b; //   add a tmp var at top of function:

    case Add:
        gen((int*)n[1]);  *++e = PSH; b = e; gen(n + 2);
        if ((e - b) == 2 && b[1] == IMM) {
           *b = AddIMM; b[1] = b[2]; e = ++b;
        }
        else *++e = ADD;
        break;

By doing this, three IR instructions become one, so less iterations of run():

PUSH
IMM 1    --> AddIMM 1
ADD

And also, push/pop overhead is reduced.

I would have made the pull request myself, but I can't compile your code in my programming environment.

I suggest you test it with Advent of Code day8. Just an AddIMM and SubIMM should speed it significantly.

Please post timing results in your pshell thread at raspberrypi.com.  Thanks.

**Comment by lurk101** [comment]
Good suggestions, but the VM version was only a step towards native code generation and is no longer under development.
