### ISSUE TITLE
document how to connect

### ISSUE THREAD

**Issue by farvardin** [lurk101/pshell#9]
hello,

it's a nice project!

you should document on the readme how to connect to the pico once it has been flashed.

for example using screen or minicom on Linux:

```
copy the pshell_usb.uf2 into your raspberry pico
screen /dev/ttyACM0 115200
# or
minicom -b 115200 -D /dev/ttyACM0
```

even "screen /dev/ttyACM0" should be enough btw
(I found some help from this website https://michlstechblog.info/blog/raspberry-pi-serial-console/)

**Comment by lurk101** [comment]
Thanks, I'll do that

**Comment by lurk101** [comment]
getting started added
